root: true
plugins:
  - react
extends:
  - react-app
  - react-app/jest
  - 'eslint:recommended'
  - 'prettier'
env:
  es2022: true
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  no-unused-vars: warn
